// User

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const ADD_DEVICE_USER = 'ADD_DEVICE_USER';
export const ADD_DEVICE_USER_SUCCESS = 'ADD_DEVICE_USER_SUCCESS';
export const ADD_DEVICE_USER_ERROR = 'ADD_DEVICE_USER_ERROR';

export const DEL_DEVICE_USER = 'DEL_DEVICE_USER';
export const DEL_DEVICE_USER_SUCCESS = 'DEL_DEVICE_USER_SUCCESS';
export const DEL_DEVICE_USER_ERROR = 'DEL_DEVICE_USER_ERROR';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_ERROR = 'GET_USER_BY_ID_ERROR';

export const GET_EQUIPMENT_TEACHER = 'GET_EQUIPMENT_TEACHER';
export const GET_EQUIPMENT_TEACHER_SUCCESS = 'GET_EQUIPMENT_TEACHER_SUCCESS';
export const GET_EQUIPMENT_TEACHER_ERROR = 'GET_EQUIPMENT_TEACHER_ERROR';

export const ATTENDANCE_STUDENT = 'ATTENDANCE_STUDENT';
export const ATTENDANCE_STUDENT_SUCCESS = 'ATTENDANCE_STUDENT_SUCCESS';
export const ATTENDANCE_STUDENT_ERROR = 'ATTENDANCE_STUDENT_ERROR';

export const GET_STATUS_ATTENDANCE = 'GET_STATUS_ATTENDANCE';
export const GET_STATUS_ATTENDANCE_SUCCESS = 'GET_STATUS_ATTENDANCE_SUCCESS';
export const GET_STATUS_ATTENDANCE_ERROR = 'GET_STATUS_ATTENDANCE_ERROR';

export const REGISTER_COURSE = 'REGISTER_COURSE';
export const REGISTER_COURSE_SUCCESS = 'REGISTER_COURSE_SUCCESS';
export const REGISTER_COURSE_ERROR = 'REGISTER_COURSE_ERROR';

export const CHANGE_PROFILE = 'CHANGE_PROFILE';

export const SAVE_PROFILE = 'SAVE_PROFILE';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_ERROR = 'SAVE_PROFILE_ERROR';

// COURSE

export const GET_COURSE_STUDENT = 'GET_COURSE_STUDENT';
export const GET_COURSE_STUDENT_SUCCESS = 'GET_COURSE_STUDENT_SUCCESS';
export const GET_COURSE_STUDENT_ERROR = 'GET_COURSE_STUDENT_ERROR';

export const GET_COURSE_BY_ID = 'GET_COURSE_BY_ID';
export const GET_COURSE_BY_ID_SUCCESS = 'GET_COURSE_BY_ID_SUCCESS';
export const GET_COURSE_BY_ID_ERROR = 'GET_COURSE_BY_ID_ERROR';

export const GET_COURSE_BY_SUB = 'GET_COURSE_BY_SUB';
export const GET_COURSE_BY_SUB_SUCCESS = 'GET_COURSE_BY_SUB_SUCCESS';
export const GET_COURSE_BY_SUB_ERROR = 'GET_COURSE_BY_SUB_ERROR';

export const GET_COURSE_ALL_BY_SUB = 'GET_COURSE_ALL_BY_SUB';
export const GET_COURSE_ALL_BY_SUB_SUCCESS = 'GET_COURSE_ALL_BY_SUB_SUCCESS';
export const GET_COURSE_ALL_BY_SUB_ERROR = 'GET_COURSE_ALL_BY_SUB_ERROR';

export const COURSE_SIZE = 6;

// SCHEDULE

export const GET_SCHEDULE_BY_DATE = 'GET_SCHEDULE_BY_DATE';
export const GET_SCHEDULE_BY_DATE_SUCCESS = 'GET_SCHEDULE_BY_DATE_SUCCESS';
export const GET_SCHEDULE_BY_DATE_ERROR = 'GET_SCHEDULE_BY_DATE_ERROR';

// SUBJECT

export const GET_SUBJECT_BY_ID = 'GET_SUBJECT_BY_ID';
export const GET_SUBJECT_BY_ID_SUCCESS = 'GET_SUBJECT_BY_ID_SUCCESS';
export const GET_SUBJECT_BY_ID_ERROR = 'GET_SUBJECT_BY_ID_ERROR';

export const GET_SUBJECT = 'GET_SUBJECT';
export const GET_SUBJECT_SUCCESS = 'GET_SUBJECT_SUCCESS';
export const GET_SUBJECT_ERROR = 'GET_SUBJECT_ERROR';

export const GET_SUBJECT_ALL = 'GET_SUBJECT_ALL';
export const GET_SUBJECT_ALL_SUCCESS = 'GET_SUBJECT_ALL_SUCCESS';
export const GET_SUBJECT_ALL_ERROR = 'GET_SUBJECT_ALL_ERROR';

export const SUBJECT_SIZE = 6;
